### ISSUE TITLE
"Error: Request Failed with status 400 - Bad Request"

### ISSUE THREAD

**Issue by LightningManGTS** [BigThunderSR/node-red-contrib-onstar2#60]
Today I started to get bad request errors

I double checked that my login info for onstar was correct and it is. 

![image](https://github.com/BigThunderSR/node-red-contrib-onstar2/assets/3919521/f8b2ba35-c2ba-4ac6-98d2-17a68e2eb527)

**Comment by LightningManGTS** [comment]
Can confirm that after restarting Node Red I was successfully able to send commands again.

**Comment by mdezzi** [comment]
I am now getting the 400 error on all requests. Is this another instance of GM blocking the key(s) used in the upstream onstarJS library?

**Comment by mdezzi** [comment]
> > @BigThunderSR I am now getting the 400 error on all requests. Is this another instance of GM blocking the key(s) used in the upstream onstarJS library?
> 
> It's working for me. Are you running the latest version?

I just realized i was on an old version. I just updated and restarted Node Red. Looks like its working. Sorry about that. 
Any idea how to pull a current vs latest version into a flow so i can notify myself when you push a new version?
